### PR TITLE
Search feature

### PR DESCRIPTION
**Pull request by znjs**
Implemented Search feature

Deploy preview: [link](https://deploy-preview-6--snowstore-react.netlify.app/)

### CODE REVIEW

**Review by Tarandeep-s1ngh — APPROVED** [review]
Everything looks good.

- Good practices followed
- dividing the code into multiple components

**Review by manismk — APPROVED** [review]
Good naming convention.
Code is easy to understand

**Review by Pratik1005 — APPROVED** [review]
Search functionality is working properly, good UI.

**Review by Nishant-96 — APPROVED** [review]
Everything looks fine. 
-I Like how you have kept  functions and components separately. 
-And the atomic css approach.

**Pull request merged**
